### ISSUE TITLE
Missing documentation (tremly.js website down)

### ISSUE THREAD

**Issue by level0dev** [Kirkhammetz/termly.js#8]
It seems that termlyjs.info is down and I can't find the docs anywhere else. 
Could the docs be uploaded to github to allow for easier hacking?

**Comment by insanity54** [comment]
Looks like the docs are in the gh-pages branch. https://github.com/Kirkhammetz/termly.js/tree/gh-pages

**Comment by simonecorsi** [comment]
Hey, sorry for not answering but I've been really busy with work.
I've moved docs to gh-pages in 8181b2125945aa8fc161da10cfae85b6d5cba3c3 since I don't have that domain anymore, you can find it here [Documentations](https://kirkhammetz.github.io/termly.js)
